font_family JetBrainsMono Nerd Font
font_size 12.0
bold_font auto
italic_font auto
bold_italic_font auto

background #030a03
foreground #b6ff9c
cursor #39ff14
selection_background #123d0d
selection_foreground #d8ffdd

color0 #030a03
color1 #ff3030
color2 #39ff14
color3 #fff27a
color4 #73ff91
color5 #b6ff9c
color6 #72ffd4
color7 #d8ffdd
color8 #123d0d
color9 #ff6666
color10 #7aff89
color11 #fff8a8
color12 #9aff78
color13 #c8ffd0
color14 #9dff7a
color15 #ffffff

window_padding_width 10
window_border_width 1pt
active_border_color #39ff14
inactive_border_color #176d28

cursor_shape beam
cursor_blink_interval 0.5
scrollback_lines 10000
enable_audio_bell no
confirm_os_window_close 0
hide_window_decorations yes

map ctrl+shift+enter new_window_with_cwd
map ctrl+shift+t new_tab_with_cwd
