color_theme = "nuclear"
truecolor = True
rounded_corners = True
proc_left = PID
proc_sorting = cpu lazy
proc_reversed = False
proc_tree = False
proc_colors = True
proc_gradient = True
proc_cores = True
show_uptime = True
show_cpu_freq = True
show_gpu_info = auto
clock_format = %H:%M:%S
